// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (slug, title, description, body, author_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, title, description, body, author_id, created_at, updated_at
`

type CreateArticleParams struct {
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Body        string    `json:"body"`
	AuthorID    uuid.UUID `json:"author_id"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.AuthorID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE slug = $1 AND author_id = $2
`

type DeleteArticleParams struct {
	Slug     string    `json:"slug"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) DeleteArticle(ctx context.Context, arg DeleteArticleParams) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, arg.Slug, arg.AuthorID)
	return err
}

const favoriteArticle = `-- name: FavoriteArticle :exec
INSERT INTO favorites (user_id, article_id)
SELECT $1, id FROM articles WHERE slug = $2
ON CONFLICT DO NOTHING
`

type FavoriteArticleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Slug   string    `json:"slug"`
}

func (q *Queries) FavoriteArticle(ctx context.Context, arg FavoriteArticleParams) error {
	_, err := q.db.ExecContext(ctx, favoriteArticle, arg.UserID, arg.Slug)
	return err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT a.id, a.slug, a.title, a.description, a.body, a.author_id, a.created_at, a.updated_at, u.username AS author_username, u.bio AS author_bio, u.image AS author_image
FROM articles a
JOIN users u ON u.id = a.author_id
WHERE a.slug = $1
`

type GetArticleBySlugRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	Body           string    `json:"body"`
	AuthorID       uuid.UUID `json:"author_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	AuthorUsername string    `json:"author_username"`
	AuthorBio      string    `json:"author_bio"`
	AuthorImage    string    `json:"author_image"`
}

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorBio,
		&i.AuthorImage,
	)
	return i, err
}

const getFavoritesCount = `-- name: GetFavoritesCount :one
SELECT COUNT(*) FROM favorites WHERE article_id = (SELECT id FROM articles WHERE slug = $1)
`

func (q *Queries) GetFavoritesCount(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFavoritesCount, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isFavorited = `-- name: IsFavorited :one
SELECT EXISTS(
  SELECT 1 FROM favorites
  WHERE user_id = $1
    AND article_id = (SELECT id FROM articles WHERE slug = $2)
)
`

type IsFavoritedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Slug   string    `json:"slug"`
}

func (q *Queries) IsFavorited(ctx context.Context, arg IsFavoritedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFavorited, arg.UserID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listArticles = `-- name: ListArticles :many
SELECT a.id, a.slug, a.title, a.description, a.body, a.author_id, a.created_at, a.updated_at, u.username AS author_username, u.bio AS author_bio, u.image AS author_image
FROM articles a
JOIN users u ON u.id = a.author_id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListArticlesRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	Body           string    `json:"body"`
	AuthorID       uuid.UUID `json:"author_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	AuthorUsername string    `json:"author_username"`
	AuthorBio      string    `json:"author_bio"`
	AuthorImage    string    `json:"author_image"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesRow
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorBio,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByTag = `-- name: ListArticlesByTag :many
SELECT a.id, a.slug, a.title, a.description, a.body, a.author_id, a.created_at, a.updated_at, u.username AS author_username, u.bio AS author_bio, u.image AS author_image
FROM articles a
JOIN users u ON u.id = a.author_id
JOIN article_tags at ON at.article_id = a.id
JOIN tags t ON t.id = at.tag_id
WHERE t.name = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListArticlesByTagParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListArticlesByTagRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	Body           string    `json:"body"`
	AuthorID       uuid.UUID `json:"author_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	AuthorUsername string    `json:"author_username"`
	AuthorBio      string    `json:"author_bio"`
	AuthorImage    string    `json:"author_image"`
}

func (q *Queries) ListArticlesByTag(ctx context.Context, arg ListArticlesByTagParams) ([]ListArticlesByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByTag, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesByTagRow
	for rows.Next() {
		var i ListArticlesByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorBio,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfavoriteArticle = `-- name: UnfavoriteArticle :exec
DELETE FROM favorites
WHERE user_id = $1
  AND article_id = (SELECT id FROM articles WHERE slug = $2)
`

type UnfavoriteArticleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Slug   string    `json:"slug"`
}

func (q *Queries) UnfavoriteArticle(ctx context.Context, arg UnfavoriteArticleParams) error {
	_, err := q.db.ExecContext(ctx, unfavoriteArticle, arg.UserID, arg.Slug)
	return err
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET
  slug        = COALESCE($2,        slug),
  title       = COALESCE($3,       title),
  description = COALESCE($4, description),
  body        = COALESCE($5,         body),
  updated_at  = NOW()
WHERE id = $1
RETURNING id, slug, title, description, body, author_id, created_at, updated_at
`

type UpdateArticleParams struct {
	ID          uuid.UUID      `json:"id"`
	Slug        sql.NullString `json:"slug"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Body        sql.NullString `json:"body"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticle,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
