// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (body, author_id, article_id)
SELECT $1, $2, id FROM articles WHERE slug = $3
RETURNING id, body, author_id, article_id, created_at, updated_at
`

type CreateCommentParams struct {
	Body     string    `json:"body"`
	AuthorID uuid.UUID `json:"author_id"`
	Slug     string    `json:"slug"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.Body, arg.AuthorID, arg.Slug)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.AuthorID,
		&i.ArticleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1 AND author_id = $2
`

type DeleteCommentParams struct {
	ID       uuid.UUID `json:"id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, deleteComment, arg.ID, arg.AuthorID)
	return err
}

const getCommentsByArticle = `-- name: GetCommentsByArticle :many
SELECT c.id, c.body, c.author_id, c.article_id, c.created_at, c.updated_at, u.username AS author_username, u.bio AS author_bio, u.image AS author_image
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.article_id = (SELECT id FROM articles WHERE slug = $1)
ORDER BY c.created_at DESC
`

type GetCommentsByArticleRow struct {
	ID             uuid.UUID `json:"id"`
	Body           string    `json:"body"`
	AuthorID       uuid.UUID `json:"author_id"`
	ArticleID      uuid.UUID `json:"article_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	AuthorUsername string    `json:"author_username"`
	AuthorBio      string    `json:"author_bio"`
	AuthorImage    string    `json:"author_image"`
}

func (q *Queries) GetCommentsByArticle(ctx context.Context, slug string) ([]GetCommentsByArticleRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByArticle, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByArticleRow
	for rows.Next() {
		var i GetCommentsByArticleRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.AuthorID,
			&i.ArticleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorBio,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
