// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddTagToArticle(ctx context.Context, arg AddTagToArticleParams) error
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArticle(ctx context.Context, arg DeleteArticleParams) error
	DeleteComment(ctx context.Context, arg DeleteCommentParams) error
	FavoriteArticle(ctx context.Context, arg FavoriteArticleParams) error
	FollowUser(ctx context.Context, arg FollowUserParams) error
	GetAllTags(ctx context.Context) ([]string, error)
	GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error)
	GetCommentsByArticle(ctx context.Context, slug string) ([]GetCommentsByArticleRow, error)
	GetFavoritesCount(ctx context.Context, slug string) (int64, error)
	GetTagsForArticle(ctx context.Context, articleID uuid.UUID) ([]string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IsFavorited(ctx context.Context, arg IsFavoritedParams) (bool, error)
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error)
	ListArticlesByTag(ctx context.Context, arg ListArticlesByTagParams) ([]ListArticlesByTagRow, error)
	UnfavoriteArticle(ctx context.Context, arg UnfavoriteArticleParams) error
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) error
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertTag(ctx context.Context, name string) (Tag, error)
}

var _ Querier = (*Queries)(nil)
