// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTagToArticle = `-- name: AddTagToArticle :exec
INSERT INTO article_tags (article_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToArticleParams struct {
	ArticleID uuid.UUID `json:"article_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToArticle(ctx context.Context, arg AddTagToArticleParams) error {
	_, err := q.db.ExecContext(ctx, addTagToArticle, arg.ArticleID, arg.TagID)
	return err
}

const getAllTags = `-- name: GetAllTags :many
SELECT name FROM tags ORDER BY name
`

func (q *Queries) GetAllTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForArticle = `-- name: GetTagsForArticle :many
SELECT t.name FROM tags t
JOIN article_tags at ON at.tag_id = t.id
WHERE at.article_id = $1
`

func (q *Queries) GetTagsForArticle(ctx context.Context, articleID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
